# Generated by Django 5.0.4 on 2024-05-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_dos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
